name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  prod_release_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: release_tag_eu
        uses: cardinalby/git-tag-action@master
        env:
          TAG: "release-tag-eu"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: release_tag_au
        uses: cardinalby/git-tag-action@master
        env:
          TAG: "release-tag-au"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  awsDeploy:
    uses: ./.github/workflows/reuse-workflow.yml
    with:
      config-path: staging
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      # - name: call
      #   uses: ./.github/workflows/reuse-workflow.yml
      #   with:
      #     config-path: path string

      # - name: Install dependencies
      #   run: npm install

      # - name: Run tests
      #   run: npm run test:headless

      # - name: Build
      #   run: npm run build:prod

      # - name: Deploy
      #   if: success()
      #   run: aws s3 cp ./dist/angular-github-actions s3://angular-fe-s3/main --recursive

      # jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: "16"

#       - name: Install dependencies
#         run: npm install

#       - name: Run tests
#         run: npm run test:headless

#       - name: Build
#         run: npm run build:prod

#       - name: Deploy
#         if: success()
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: dist/angular-github-actions
#           enable_jekyll: true
